### PR TITLE
Merge pull request #647 from rannmann/prunebans-fix

### LINKED ISSUE #644: PruneBans queries taking > 20 seconds
One of the admins in my old gaming community noticed sourcebans was really slow loading the bans pages, both on the admin side and user-facing side.  I enabled the slow query logger and immediately found the root of the problem to be a 30-second query from PruneBans().

What are the steps to reproduce this issue?
-------------------------------------------
1. At least 7849 rows matching: ```SELECT DISTINCT authid FROM `sb_bans` WHERE `type` = 0 AND `RemoveType` IS NULL;```
2. At least 183 rows matching: ```SELECT DISTINCT ip FROM `sb_bans` WHERE `type` = 1 AND `RemoveType` IS NULL;```
3. Load any page with bans

What happens?
-------------
Page takes 30 seconds to load.

What were you expecting to happen?
----------------------------------
No noticeable increase to load time.

Any logs, error output, etc.?
----------------------------
Notice: Please read the section below before trying to figure out why there's so may things in this gist.  https://gist.github.com/rannmann/650b9fe26060b1a1e4a7e9b9e64e8530

Also note that **by simply adding an index** the rows examined drops from 18.7 million to 3.7 million.  The sub-selects in the update statement appear to be running per row matched, not just one time.

Any other comments?
-------------------
I wrote a rough draft fix for it.  I'm not really familiar with the sourcebans codebase, and honestly I have no idea what this query is *supposed* to be accomplishing.  But there are two key takeaways on improving this, and one further recommendation.

1. Index the field being searched on.
2. Don't run sub-queries in update statements.
3. Recommendation: Run these types of cleanup tasks after results are rendered.  Find instances of `PruneBans();` calls and toss them into `register_shutdown_function()`.  Users shouldn't have to wait for these calls to process.

I realize PruneBans() has changed in master since the latest release, but the table schema and query in appear to be unchanged.  Due to the PDO change in master, binding all the steam IDs and IP addresses is recommended rather than injecting them into the query without any kind of escaping.

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu
**SourceBans++ Version:** 1.6.3
**PHP Version:** 5.6.40
**MySQL Version:** 5.7.28
**Link to your project:** https://firepoweredgaming.com/sourcebanspp/
**Link to a phpinfo() output:** https://firepoweredgaming.com/sourcebanspp/phpinfo.php

### PR DESCRIPTION
**Pull request by rannmann**
## Description
Primarily fixes #644.  Cleans up PHPDoc in a few files, fixes some namespace issues, fixes some bad return types, and adds some minor functionality to the Database class so we can use more PDO features (used in PruneBans)

## Motivation and Context
Database query for prune bans related to the submissions table was very slow.  Split this query into multiple queries to fix it.  See #644.

## How Has This Been Tested?
Plugged a copy of a production database into these changes and loaded all the major pages, focusing mostly on the bans page.  I'm running PHP 7.3.13, but my IDE is configured to provide notices for PHP 7.1 as per the minimum requirements of this project.

PruneBans() is only called in 3 places, but takes no parameters so testing it in one context should be sufficient.

## Screenshots (if appropriate):

N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: web/includes/Database.php [hunk 1]
```diff
@@ -2,20 +2,29 @@
...
     private $stmt;
 
     public function __construct($host, $port, $dbname, $user, $password, $prefix, $charset = 'utf8')
     {
         $this->prefix = $prefix;
-        $dsn = 'mysql:host='.$host.';port='.$port.';dbname='.$dbname.';charset='.$charset;
+        $dsn = 'mysql:host=' . $host . ';port=' . $port . ';dbname=' . $dbname . ';charset=' . $charset;
         $options = array(
-            \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION
+            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
```
Comment (rannmann) [inline web/includes/Database.php:23]: We're already at a global scope.  The root notation is superfluous.

File: web/includes/Database.php [hunk 2]
```diff
@@ -26,93 +35,142 @@ public function __destruct()
...
 
-    public function execute()
+    /**
+     * @param null|array $inputParams
+     * @return mixed
+     */
+    public function execute(?array $inputParams = null)
     {
-        return $this->stmt->execute();
+        return $this->stmt->execute($inputParams);
```
Comment (rannmann) [inline web/includes/Database.php:106]: We can now bind nameless params at execution time.

File: web/includes/Database.php [hunk 3]
```diff
@@ -26,93 +35,142 @@ public function __destruct()
...
     }
 
-    public function resultset()
+    /**
+     * @param null|array $inputParams
+     * @param int $fetchType
+     * @return mixed
+     */
+    public function resultset(?array $inputParams = null, $fetchType = PDO::FETCH_ASSOC)
```
Comment (rannmann) [inline web/includes/Database.php:114]: We can now bind nameless params at execution time, and choose the fetch mode ourselves.

File: web/includes/Database.php [hunk 4]
```diff
@@ -26,93 +35,142 @@ public function __destruct()
...
+        return $this->stmt->fetchAll($fetchType);
     }
 
-    public function single()
+    /**
+     * @param null|array $inputParams
+     * @param int $fetchType
+     * @return mixed
+     */
+    public function single(?array $inputParams = null, $fetchType = PDO::FETCH_ASSOC)
```
Comment (rannmann) [inline web/includes/Database.php:125]: We can now bind nameless params at execution time, and choose the fetch mode ourselves.

File: web/includes/system-functions.php [hunk 5]
```diff
@@ -35,6 +36,8 @@
  * @param string $url The link
  * @param string $tooltip The tooltip message
  * @param string $target The new links target
+ * @param bool $wide
+ * @param string $onclick
```
Comment (rannmann) [inline web/includes/system-functions.php:40]: Added missing params from phpdoc

File: web/includes/system-functions.php [hunk 6]
```diff
@@ -63,10 +70,13 @@ function BitToString($mask)
         }
     }
 
-    return $out;
+    return isset($out) ? $out : false;
```
Comment (rannmann) [inline web/includes/system-functions.php:73]: Fixes potential php warning about $out not being defined.

File: web/includes/system-functions.php [hunk 7]
```diff
@@ -81,25 +91,40 @@ function SmFlagsToSb($flagstring)
...
```
Comment (rannmann) [inline web/includes/system-functions.php:94]: Fixes potential php warning about $out not being defined.

File: web/includes/system-functions.php [hunk 8]
```diff
@@ -175,18 +220,47 @@ function PruneBans()
...
-    $GLOBALS['PDO']->query(
-        "UPDATE `:prefix_submissions` SET `archiv` = 3, `archivedby` = :id
-        WHERE `archiv` = 0 AND
-        (SteamId IN(SELECT authid FROM `:prefix_bans` WHERE type = 0 AND RemoveType IS NULL)
-        OR sip IN(SELECT ip FROM `:prefix_bans` WHERE type = 1 AND RemoveType IS NULL))"
-    );
-    $GLOBALS['PDO']->bind(':id', $userbank->GetAid() < 0 ? 0 : $userbank->GetAid());
+    $GLOBALS['PDO']->bind(':id', $adminId);
     $GLOBALS['PDO']->execute();
+
```
Comment (rannmann) [inline web/includes/system-functions.php:225]: Here's the main change.

File: web/includes/system-functions.php [hunk 9]
```diff
@@ -196,14 +270,23 @@ function PruneComms()
     $GLOBALS['PDO']->execute();
 }
 
+/**
+ * @param string $dir
+ * @return string
+ */
 function getDirSize($dir)
 {
+    $size = 0;
```
Comment (rannmann) [inline web/includes/system-functions.php:279]: Fixes PHP warning about size not being defined if the foreach loop doesn't run

File: web/includes/system-functions.php [hunk 10]
```diff
@@ -213,15 +296,20 @@ function sizeFormat($bytes)
...
+ * @return array array('STEAM_ID_1' => array('name' => $name, 'steam' => $steam, 'ip' => $ip, 'time' => $time, 'ping' => $ping), 'STEAM_ID_2' => array()....)
+ */
 function checkMultiplePlayers(int $sid, $steamids)
 {
     $ret = rcon('status', $sid);
 
-    if (!$ret)
-        return false;
+    if (!$ret) {
+        return [];
```
Comment (rannmann) [inline web/includes/system-functions.php:311]: This method is only used in 1 place, and the result is always treated like an array.  It was never checked for a false value.

File: web/includes/system-functions.php [hunk 11]
```diff
@@ -262,30 +359,35 @@ function rcon(string $cmd, int $sid)
         $rcon->setRconPassword($server['rcon']);
 
         $output = $rcon->Rcon($cmd);
-    } catch (AuthenticationException $e) {
+    } catch (\xPaw\SourceQuery\Exception\AuthenticationException $e) {
```
Comment (rannmann) [inline web/includes/system-functions.php:362]: Class was unknown.  Not sure what happened in the past if this code was ever reached.

File: web/includes/system-functions.php [hunk 12]
```diff
@@ -262,30 +359,35 @@ function rcon(string $cmd, int $sid)
...
 
         $output = $rcon->Rcon($cmd);
-    } catch (AuthenticationException $e) {
+    } catch (\xPaw\SourceQuery\Exception\AuthenticationException $e) {
         $GLOBALS['PDO']->query("UPDATE `:prefix_servers` SET rcon = '' WHERE sid = :sid");
         $GLOBALS['PDO']->bind(':sid', $sid);
         $GLOBALS['PDO']->execute();
 
-        Log::add('e', "Rcon Password Error [ServerID: $sid]", $e->getMessage);
+        Log::add('e', "Rcon Password Error [ServerID: $sid]", $e->getMessage());
```
Comment (rannmann) [inline web/includes/system-functions.php:367]: Exceptions don't have this property, but they do have this method.

File: web/includes/system-functions.php [hunk 13]
```diff
@@ -262,30 +359,35 @@ function rcon(string $cmd, int $sid)
...
+ * @return array
+ */
 function parseRconStatus(string $status)
 {
     $regex = '/#\s*(\d+)(?>\s|\d)*"(.*)"\s*(STEAM_[01]:[01]:\d+|\[U:1:\d+\])(?>\s|:|\d)*[a-zA-Z]*\s*\d*\s*([0-9.]+)/';
     $players = [];
 
-    preg_match_all($regex, $status, $status, PREG_SET_ORDER);
+    $result = [];
+    preg_match_all($regex, $status, $result, PREG_SET_ORDER);
```
Comment (rannmann) [inline web/includes/system-functions.php:388]: Don't put the results back into the original variable that held the string.  This fixes PHPStorm's warnings.
